# Generated by Django 4.2.27 on 2026-03-04 08:50
# Modified for Django 3.0 compatibility: Replaced RenameIndex with RemoveIndex+AddIndex

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('bitcoincash_oauth_django', '0001_initial'),
    ]

    operations = [
        # RenameIndex is Django 4.2+ only. Use RemoveIndex + AddIndex for Django 3.0 compat.
        migrations.RemoveIndex(
            model_name='oauthtoken',
            name='bitcoincash_user_revok_1f8f66_idx',
        ),
        migrations.AddIndex(
            model_name='oauthtoken',
            index=models.Index(fields=['user', 'is_revoked', 'expires_at'], name='bitcoincash_user_id_950995_idx'),
        ),
        migrations.RemoveIndex(
            model_name='oauthtoken',
            name='bitcoincash_created_3c9f6b_idx',
        ),
        migrations.AddIndex(
            model_name='oauthtoken',
            index=models.Index(fields=['created_at'], name='bitcoincash_created_c8424c_idx'),
        ),
        migrations.AddField(
            model_name='bitcoincashuser',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='bitcoincashuser',
            name='password',
            field=models.CharField(default='', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bitcoincashuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='bitcoincashuser_groups', related_query_name='bitcoincashuser', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='bitcoincashuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='bitcoincashuser_user_permissions', related_query_name='bitcoincashuser', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
